Reverse changes to bare bone working sublcass
- will start from here for debugging
- currently, trying to use this subclass fails with the following (when running run_tests.sh on yt_videos_list package):

```
[MainThread] 2021-01-09T21:53:58.320406: Running tests!
Traceback (most recent call last):
  File "/Users/shail/yt_videos_list/python/tests/test_all_drivers.py", line 34, in <module>
    main()
  File "/Users/shail/yt_videos_list/python/tests/test_all_drivers.py", line 24, in main
    test_cross_platform_drivers.main()
  File "/Users/shail/yt_videos_list/python/tests/test_cross_platform_drivers.py", line 39, in main
    run_tests_for(browsers)
  File "/Users/shail/yt_videos_list/python/tests/test_shared.py", line 99, in run_tests_for
    test_case_thread_1 = ThreadWithResult(target=run_test_case, args=(thread_1_case, log_1_name))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/save_thread_result/thread_with_result.py", line 49, in __init__
    self.name                 = name
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1066, in name
    assert self._initialized, "Thread.__init__() not called"
AssertionError: Thread.__init__() not called
```

- changing the super class to any of the following did NOT work:

```
threading.Thread().__init__(group, target=function, name=self.name, args=(), kwargs={}, daemon=daemon)
threading.Thread().__init__(group=self.group, target=function, name=self.name, args=(), kwargs={}, daemon=self.daemon)
super().__init__(group=self.group, target=function, name=self.name, args=(), kwargs={}, daemon=self.daemon)
super().__init__()
```