Assign only target, args, & kwargs as subclass attributes
- this avoids the problem of

```
AssertionError: Thread.__init__() not called
```

- the problem **MIGHT** be because we are overriding the __init__ method from the threading.Thread class by assigning ALL attributes within the subclass
- resources:
  - https://stackoverflow.com/a/16978085
    - "And your second try using the set method works, because you are not overriding the `__init__` method from Thread therefore the original init method from the parent class is used it runs as it is supposed.
  - https://realpython.com/python-super/