Include subclass attributes as instance attiributes
- `zsh tests/run_tests.sh` in yt_videos_list NO LONGER works!
  - fails with the following message:

```
===>>>[MainThread] 2021-01-09T22:13:29.517728: Running tests!
Traceback (most recent call last):
  File "/Users/shail/yt_videos_list/python/tests/test_all_drivers.py", line 34, in <module>
    main()
  File "/Users/shail/yt_videos_list/python/tests/test_all_drivers.py", line 24, in main
    test_cross_platform_drivers.main()
  File "/Users/shail/yt_videos_list/python/tests/test_cross_platform_drivers.py", line 39, in main
    run_tests_for(browsers)
  File "/Users/shail/yt_videos_list/python/tests/test_shared.py", line 99, in run_tests_for
    test_case_thread_1 = ThreadWithResult(target=run_test_case, args=(thread_1_case, log_1_name))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/save_thread_result/thread_with_result.py", line 51, in __init__
    self.name                 = name
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1066, in name
    assert self._initialized, "Thread.__init__() not called"
AssertionError: Thread.__init__() not called
```